"use strict";

module.exports = function(sequelize, DataTypes) {
  var Family = sequelize.define("Family", {
    Registrynumber: DataTypes.STRING(10),
    Recordnumber: DataTypes.STRING(12),
  	FamilyRecordDate: DataTypes.DATEONLY(),
  	Autogenerated_Id: DataTypes.BIGINT() ,
  	Is_Closed: {type:DataTypes.INTEGER(2),defaultValue:1},
    FamilyType:{type:DataTypes.INTEGER(1),defaultValue:1}, 
  	status:{type:DataTypes.INTEGER(1),defaultValue:1} 
  }, {
    classMethods: {
      associate: function(models) {
        Family.belongsTo(models.Office, {
          onDelete: "restrict",
          foreignKey: {
            allowNull: false
          }
        });
      }
    }
  });
  return Family;
};
